// 用户信息
export const SET_USER_INFO = 'SET_USER_INFO';

// 护照手术信息
export const SET_PASSPORT_SURGERY_INFO = 'SET_PASSPORT_SURGERY_INFO';

// 护照病理信息
export const SET_PASSPORT_PATHOLOGY_INFO = 'SET_PASSPORT_PATHOLOGY_INFO';

// 护照治疗信息
export const SET_PASSPORT_TREATMENT_INFO = 'SET_PASSPORT_TREATMENT_INFO';

// 护照报告信息
export const SET_PASSPORT_REPORT_INFO = 'SET_PASSPORT_REPORT_INFO';

// 护照选择的报告
export const SET_PASSPORT_SELECTED_REPORT = 'SET_PASSPORT_SELECTED_REPORT';

// 问诊医院列表
export const SET_CONSULT_HOSPITAL_LIST = 'SET_CONSULT_HOSPITAL_LIST';

// 问诊医生列表
export const SET_CONSULT_DOCTOR_LIST = 'SET_CONSULT_DOCTOR_LIST';

// 问诊选择的医院
export const SET_CONSULT_SELECTED_HOSPITAL = 'SET_CONSULT_SELECTED_HOSPITAL';

// 问诊选择的医生
export const SET_CONSULT_SELECTED_DOCTOR = 'SET_CONSULT_SELECTED_DOCTOR';

// 问诊服务列表
export const SET_CONSULT_SERVER_LIST = 'SET_CONSULT_SERVER_LIST';

// 问诊当前购买的订单
export const SET_CONSULT_CURR_BUY_ORDER = 'SET_CONSULT_CURR_BUY_ORDER';

// 问诊已购买的医生
export const SET_CONSULT_PURCHASED_DOCTORS = 'SET_CONSULT_PURCHASED_DOCTORS';

// 最近消息map
export const SET_CONSULT_LATEST_MSG_MAP = 'SET_CONSULT_LATEST_MSG_MAP';

// 当前聊天的医生
export const SET_CONSULT_CURR_CHAT_DOCTOR = 'SET_CONSULT_CURR_CHAT_DOCTOR';

// 当前聊天的订单
export const SET_CONSULT_CURR_CHAT_ORDER = 'SET_CONSULT_CURR_CHAT_ORDER';

// 聊天消息
export const SET_CONSULT_CHAT_MSG_LIST = 'SET_CONSULT_CHAT_MSG_LIST';

// 插入聊天信息
export const PUSH_CONSULT_CHAT_MSG = 'PUSH_CONSULT_CHAT_MSG';

// 问诊单
export const SET_CONSULT_SHEET = 'SET_CONSULT_SHEET';

// 已支付订单
export const SET_ORDER_PAYED_LIST = 'SET_ORDER_PAYED_LIST';

// 未支付订单
export const SET_ORDER_UNPAY_LIST = 'SET_ORDER_UNPAY_LIST';

// 当前选择的订单
export const SET_ORDER_CURR_SELECTED = 'SET_ORDER_CURR_SELECTED';

// 已经购买的医生
export const SET_ORDER_PURCHASED_DOCTORS = 'SET_ORDER_PURCHASED_DOCTORS';

// 注册手机号
export const SET_REGISTER_PHONE = 'SET_REGISTER_PHONE';

// 注册短信验证码
export const SET_REGISTER_VERIFY_CODE = 'SET_REGISTER_VERIFY_CODE';

// 手机验证码倒计时
export const SET_REGISTER_CODE_TIME = 'SET_REGISTER_CODE_TIME';

// 是否显示倒计时
export const SET_REGISTER_CODE_TIME_SHOW = 'SET_REGISTER_CODE_TIME_SHOW';
