// 用户信息
export const SET_USER_INFO = 'SET_USER_INFO';

// 问诊医院列表
export const SET_CONSULT_HOSPITAL_LIST = 'SET_CONSULT_HOSPITAL_LIST';

// 问诊医生列表
export const SET_CONSULT_DOCTOR_LIST = 'SET_CONSULT_DOCTOR_LIST';

// 问诊所有医生
export const SET_CONSULT_ALL_DOCTORS = 'SET_CONSULT_ALL_DOCTORS';

// 问诊选择的医院
export const SET_CONSULT_SELECTED_HOSPITAL = 'SET_CONSULT_SELECTED_HOSPITAL';

// 问诊选择的医生
export const SET_CONSULT_SELECTED_DOCTOR = 'SET_CONSULT_SELECTED_DOCTOR';

// 问诊服务列表
export const SET_CONSULT_SERVER_LIST = 'SET_CONSULT_SERVER_LIST';

// 问诊选择的服务
export const SET_CONSULT_SELECTED_SERVER = 'SET_CONSULT_SELECTED_SERVER';

// 聊天医生列表
export const SET_CONSULT_CHAT_DOCTOR_LIST = 'SET_CONSULT_CHAT_DOCTOR_LIST';
